export const COMPANIES = [
  {
    "name": "Google",
    "category": "Global MNC",
    "sector": "Search / Cloud",
    "roles": "SWE, SDE-1, Backend",
    "ctc": "₹30–45 LPA",
    "score": 4.1,
    "diff": "Very Hard",
    "isnew": false,
    "careers": "https://www.google.com/about/careers/applications/jobs/results/?q&hl=en-GB&location=India"
  },
  {
    "name": "Meta",
    "category": "Global MNC",
    "sector": "Social / AI",
    "roles": "SWE, Backend Eng",
    "ctc": "₹25–40 LPA",
    "score": 4,
    "diff": "Very Hard",
    "isnew": false,
    "careers": "https://www.metacareers.com/jobsearch?offices[0]=Mumbai%2C%20India&offices[1]=Gurgaon%2C%20India&offices[2]=Bangalore%2C%20India&offices[3]=Hyderabad%2C%20India&offices[4]=New%20Delhi%2C%20India"
  },
  {
    "name": "Amazon",
    "category": "Global MNC",
    "sector": "E-comm / Cloud",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹18–35 LPA",
    "score": 3.7,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.amazon.jobs/en/search?base_query=&loc_query=India&country=IND"
  },
  {
    "name": "Adobe",
    "category": "Global MNC",
    "sector": "Creative SaaS",
    "roles": "MTS-1, SDE-1",
    "ctc": "₹20–30 LPA",
    "score": 3.6,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://careers.adobe.com/us/en/search-results?qcountry=India"
  },
  {
    "name": "Atlassian",
    "category": "Global MNC",
    "sector": "Dev Tools",
    "roles": "Graduate SWE, SDE-1",
    "ctc": "₹18–28 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.atlassian.com/company/careers/all-jobs?team=&location=India&search="
  },
  {
    "name": "Salesforce",
    "category": "Global MNC",
    "sector": "CRM SaaS",
    "roles": "Assoc SWE, Backend",
    "ctc": "₹15–25 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.salesforce.com/company/careers/jobs/?country=India&page=1"
  },
  {
    "name": "Intuit",
    "category": "Global MNC",
    "sector": "FinTech SaaS",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹14–22 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://jobs.intuit.com/search-jobs/India/27595/2/1269750/22/79/0/2"
  },
  {
    "name": "Qualcomm",
    "category": "Global MNC",
    "sector": "Semiconductors",
    "roles": "SW Engineer, Firmware",
    "ctc": "₹12–20 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://careers.qualcomm.com/careers?start=0&location=india&pid=446718418965&sort_by=match&filter_include_remote=0"
  },
  {
    "name": "Microsoft",
    "category": "Global MNC",
    "sector": "Cloud / OS",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹20–45 LPA",
    "score": 3.8,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://apply.careers.microsoft.com/careers?query=&location=&start=0"
  },
  {
    "name": "Cisco",
    "category": "Global MNC",
    "sector": "Networking",
    "roles": "SW Engineer, SDE",
    "ctc": "₹10–18 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.cisco.com/global/en/search-results"
  },
  {
    "name": "Oracle",
    "category": "Global MNC",
    "sector": "DB / Cloud",
    "roles": "Assoc Developer",
    "ctc": "₹10–18 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.oracle.com/en/sites/jobsearch/jobs?lastSelectedFacet=CATEGORIES&location=India&locationId=300000000106947&locationLevel=country&mode=location&selectedCategoriesFacet=300000001917356"
  },
  {
    "name": "VMware (Broadcom)",
    "category": "Global MNC",
    "sector": "Virtualisation",
    "roles": "MTS, SW Engineer",
    "ctc": "₹14–22 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://broadcom.wd1.myworkdayjobs.com/External_Career?locations=6d1be12dc134103be580f2ed396f3bdf"
  },
  {
    "name": "SAP",
    "category": "Global MNC",
    "sector": "ERP SaaS",
    "roles": "Assoc Dev, Python",
    "ctc": "₹10–18 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://jobs.sap.com/search/?createNewAlert=false&q=&locationsearch=india&optionsFacetsDD_department=&optionsFacetsDD_customfield3=&optionsFacetsDD_country="
  },
  {
    "name": "Workday",
    "category": "Global MNC",
    "sector": "HR SaaS",
    "roles": "SWE, Backend Eng",
    "ctc": "₹14–20 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://workday.wd5.myworkdayjobs.com/Workday"
  },
  {
    "name": "PayPal",
    "category": "Global MNC",
    "sector": "Payments",
    "roles": "SWE, Backend Dev",
    "ctc": "₹12–18 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://paypal.eightfold.ai/careers?start=0&location=india&pid=274919648411&sort_by=distance&filter_include_remote=1"
  },
  {
    "name": "Walmart Global Tech",
    "category": "Global MNC",
    "sector": "Retail Tech",
    "roles": "SWE, SDE-1",
    "ctc": "₹14–20 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://walmart.wd5.myworkdayjobs.com/en-US/WalmartExternal?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e"
  },
  {
    "name": "Intel",
    "category": "Global MNC",
    "sector": "Semiconductors",
    "roles": "SW Engineer",
    "ctc": "₹12–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://intel.wd1.myworkdayjobs.com/External"
  },
  {
    "name": "Texas Instruments",
    "category": "Global MNC",
    "sector": "Semiconductors",
    "roles": "SW Engineer",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.ti.com/en/sites/CX/jobs?location=India&locationId=300000000361484&locationLevel=country&mode=location"
  },
  {
    "name": "IBM",
    "category": "Global MNC",
    "sector": "Cloud / AI",
    "roles": "Assoc Dev, Python Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.ibm.com/in-en/careers/search"
  },
  {
    "name": "Dell Technologies",
    "category": "Global MNC",
    "sector": "Enterprise Tech",
    "roles": "SW Developer",
    "ctc": "₹8–14 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://iawmqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/careers"
  },
  {
    "name": "Uber",
    "category": "Global MNC",
    "sector": "Mobility Tech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹20–35 LPA",
    "score": 3.8,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.uber.com/in/en/careers/list/?location=IND-Karn%C4%81taka-Bangalore&location=IND-Telang%C4%81na-Hyderabad&location=IND-Mah%C4%81r%C4%81shtra-Mumbai"
  },
  {
    "name": "LinkedIn",
    "category": "Global MNC",
    "sector": "Professional Network",
    "roles": "SWE, SDE-1",
    "ctc": "₹18–30 LPA",
    "score": 3.6,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.linkedin.com/company/linkedin/jobs/?src=direct%2Fnone&veh=direct%2Fnone"
  },
  {
    "name": "Mastercard",
    "category": "Global MNC",
    "sector": "Payments",
    "roles": "SWE, Backend Dev",
    "ctc": "₹12–20 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.mastercard.com/us/en/search-results"
  },
  {
    "name": "Visa",
    "category": "Global MNC",
    "sector": "Payments",
    "roles": "SWE, Software Dev",
    "ctc": "₹12–20 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://visa.wd5.myworkdayjobs.com/Visa"
  },
  {
    "name": "American Express",
    "category": "Global MNC",
    "sector": "Payments / Fintech",
    "roles": "SWE, Backend Dev",
    "ctc": "₹10–18 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.americanexpress.com/en/sites/CX_1/jobs?intlink=us-amex-career-en-us-search"
  },
  {
    "name": "Target (India Tech)",
    "category": "Global MNC",
    "sector": "Retail Tech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://corporate.target.com/careers/job-search?currentPage=1&schedule=Full-time&country=India"
  },
  {
    "name": "Goldman Sachs",
    "category": "Global MNC",
    "sector": "Fintech / Banking",
    "roles": "Analyst, SWE",
    "ctc": "₹15–25 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://higher.gs.com/results?LOCATION=Bengaluru|Hyderabad|Mumbai&page=1&sort=RELEVANCE"
  },
  {
    "name": "Flipkart",
    "category": "Indian Unicorn",
    "sector": "E-commerce",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹16–22 LPA",
    "score": 3.8,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://flipkart.turbohire.co/dashboardv2?orgId=4d757ba0-3d57-448a-b82c-238ed87ac90f&type=0"
  },
  {
    "name": "CRED",
    "category": "Indian Unicorn",
    "sector": "Fintech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–22 LPA",
    "score": 3.7,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://careers.cred.club/openings"
  },
  {
    "name": "Razorpay",
    "category": "Indian Unicorn",
    "sector": "Payments",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–22 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://razorpay.com/jobs/jobs-all/?location=all&department="
  },
  {
    "name": "Dream11",
    "category": "Indian Unicorn",
    "sector": "Gaming / Sports",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹12–18 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://careers.dream11.com"
  },
  {
    "name": "ShareChat / Moj",
    "category": "Indian Unicorn",
    "sector": "Social Media",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–16 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://sharechat.com/careers"
  },
  {
    "name": "Meesho",
    "category": "Indian Unicorn",
    "sector": "E-commerce",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.meesho.io/jobs?&t=Business%20Analytics,Backend,QA,Infrastructure,CTO%20Office,Data%20Engineering,Data%20Science,Demand,Frontend,Supply,Security"
  },
  {
    "name": "Swiggy",
    "category": "Indian Unicorn",
    "sector": "Foodtech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.swiggy.com/#/careers?career_page_category=Technology"
  },
  {
    "name": "Zomato",
    "category": "Indian Unicorn",
    "sector": "Foodtech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.eternal.com/careers/"
  },
  {
    "name": "PhonePe",
    "category": "Indian Unicorn",
    "sector": "Payments",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–20 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.phonepe.com/careers/job-openings/"
  },
  {
    "name": "Groww",
    "category": "Indian Unicorn",
    "sector": "WealthTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹12–18 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://job-boards.eu.greenhouse.io/groww"
  },
  {
    "name": "Zepto",
    "category": "Indian Unicorn",
    "sector": "Quick Commerce",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://zepto.talentrecruit.com/career-page"
  },
  {
    "name": "Games24x7",
    "category": "Indian Unicorn",
    "sector": "Gaming",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–14 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.games24x7.com/careers"
  },
  {
    "name": "Paytm",
    "category": "Indian Unicorn",
    "sector": "Fintech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "http://jobs.lever.co/paytm"
  },
  {
    "name": "PolicyBazaar",
    "category": "Indian Unicorn",
    "sector": "InsurTech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.policybazaar.com/careers/"
  },
  {
    "name": "BharatPe",
    "category": "Indian Unicorn",
    "sector": "Fintech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–15 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://bharatpe.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Nykaa",
    "category": "Indian Unicorn",
    "sector": "Beauty E-comm",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–15 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.nykaa.com/"
  },
  {
    "name": "Urban Company",
    "category": "Indian Unicorn",
    "sector": "Home Services",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–15 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.urbancompany.com/jobs?department=Engineering%20%26%20Data"
  },
  {
    "name": "Upstox",
    "category": "Indian Unicorn",
    "sector": "Fintech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://upstox.com/careers/"
  },
  {
    "name": "Lenskart",
    "category": "Indian Unicorn",
    "sector": "D2C Retail",
    "roles": "SDE-1, Software Eng",
    "ctc": "₹10–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://ainterviews.com/job_board/lenskart_ho/#open-positions"
  },
  {
    "name": "Zerodha",
    "category": "Indian Unicorn",
    "sector": "Stock Broking",
    "roles": "Software Eng, Python",
    "ctc": "₹10–15 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.zerodha.com/"
  },
  {
    "name": "Delhivery",
    "category": "Indian Unicorn",
    "sector": "Logistics",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–12 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://delhivery.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Ola",
    "category": "Indian Unicorn",
    "sector": "Mobility",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–16 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://olacareers.turbohire.co/careerpage/e0c1eb37-eb7a-4ca4-bcc5-d59ce4ce9212"
  },
  {
    "name": "OYO",
    "category": "Indian Unicorn",
    "sector": "Hospitality Tech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.linkedin.com/company/oyo-rooms/jobs/"
  },
  {
    "name": "PharmEasy",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://myhr.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Rapido",
    "category": "Indian Unicorn",
    "sector": "Mobility",
    "roles": "SDE-1, Software Eng",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://rapido.darwinbox.in/ms/candidatev2/main/careers/home"
  },
  {
    "name": "Porter",
    "category": "Indian Unicorn",
    "sector": "Logistics Tech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://porter.darwinbox.in/ms/candidatev2/main/careers/home"
  },
  {
    "name": "Shiprocket",
    "category": "Indian Unicorn",
    "sector": "Logistics SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://careers.shiprocket.in/?_gl=1*rn5hvt*_gcl_au*MjQ1NTgxMjkzLjE3NzkwMjQwMjc."
  },
  {
    "name": "Tata 1mg",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://1mg.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Pristyn Care",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "Backend Eng, SDE-1",
    "ctc": "₹8–12 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.pristyncare.com/careers"
  },
  {
    "name": "Acko",
    "category": "Indian Unicorn",
    "sector": "InsurTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–14 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.acko.com/careers/jobs/"
  },
  {
    "name": "Practo",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://practo.app.param.ai/jobs/"
  },
  {
    "name": "Slice",
    "category": "Indian Unicorn",
    "sector": "Fintech / Neo-bank",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–15 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://slice.bank.in/careers/open-positions"
  },
  {
    "name": "Cult.fit",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.1,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://careers.cult.fit/cult/jobslist"
  },
  {
    "name": "Physics Wallah",
    "category": "Indian Unicorn",
    "sector": "EdTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.1,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://pwhr.darwinbox.in/ms/candidatev2/a62d7a6e288992/careers/allJobs"
  },
  {
    "name": "Unacademy",
    "category": "Indian Unicorn",
    "sector": "EdTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.1,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://unacademy.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "upGrad",
    "category": "Indian Unicorn",
    "sector": "EdTech",
    "roles": "SDE-1, Software Eng",
    "ctc": "₹8–12 LPA",
    "score": 2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://upgrad.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Vedantu",
    "category": "Indian Unicorn",
    "sector": "EdTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.linkedin.com/jobs/search/?currentJobId=4399637113&f_C=3139796&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLandingJobPostings=4399637113%2C4394757689%2C4400750377%2C4392857261%2C4389532762%2C4389534337%2C4388933368%2C4389567642%2C4397271687"
  },
  {
    "name": "Myntra",
    "category": "Indian Unicorn",
    "sector": "Fashion E-comm",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–20 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://jobs.myntra.com/home"
  },
  {
    "name": "Blinkit (Zomato)",
    "category": "Indian Unicorn",
    "sector": "Quick Commerce",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.eternal.com/careers/"
  },
  {
    "name": "Hotstar (Disney+)",
    "category": "Indian Unicorn",
    "sector": "Video Streaming",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–22 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.disneycareers.com/en/search-jobs/India/391/2/1269750/22/79/100/2"
  },
  {
    "name": "MPL (Mobile Premier)",
    "category": "Indian Unicorn",
    "sector": "Gaming / E-sports",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.mpl.live"
  },
  {
    "name": "Digit Insurance",
    "category": "Indian Unicorn",
    "sector": "InsurTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://godigit.darwinbox.in/ms/candidatev2/a651fdd75445d1/careers/allJobs"
  },
  {
    "name": "BlackBuck",
    "category": "Indian Unicorn",
    "sector": "Logistics Tech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://blackbuck.com/careers"
  },
  {
    "name": "Xpressbees",
    "category": "Indian Unicorn",
    "sector": "Logistics",
    "roles": "Software Eng, Backend",
    "ctc": "₹7–11 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.xpressbees.com/career"
  },
  {
    "name": "Shadowfax",
    "category": "Indian Unicorn",
    "sector": "Logistics",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.1,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://shadowfax.in/careers"
  },
  {
    "name": "Juspay",
    "category": "Indian SaaS",
    "sector": "Payments SaaS",
    "roles": "Assoc SWE, Backend",
    "ctc": "₹10–16 LPA",
    "score": 3.7,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://juspay.io/careers"
  },
  {
    "name": "Postman",
    "category": "Indian SaaS",
    "sector": "Dev Tools",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.postman.com/company/careers/open-positions/"
  },
  {
    "name": "BrowserStack",
    "category": "Indian SaaS",
    "sector": "Testing SaaS",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–16 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://browserstack.wd3.myworkdayjobs.com/External"
  },
  {
    "name": "Freshworks",
    "category": "Indian SaaS",
    "sector": "CRM SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://careers.smartrecruiters.com/Freshworks"
  },
  {
    "name": "Sprinklr",
    "category": "Indian SaaS",
    "sector": "CX Platform",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–16 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://sprinklr.wd1.myworkdayjobs.com/careers?_gl=1*1i1giiy*_gcl_au*MzU2NzE1NTgzLjE3NzkwOTM0Mzc.*_ga*OTI0MTA5ODk3LjE3NzkwOTM0NzE.*_ga_GD43S3NXZ0*czE3NzkwOTM0NzAkbzEkZzAkdDE3NzkwOTM0NzIkajU4JGwwJGgw"
  },
  {
    "name": "Druva",
    "category": "Indian SaaS",
    "sector": "Data Protection",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–16 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": false,
    "careers": "https://www.druva.com/why-druva/explore/careers/departments/engineering"
  },
  {
    "name": "Whatfix",
    "category": "Indian SaaS",
    "sector": "Digital Adoption",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–14 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://whatfix101.hire.trakstar.com/?loc=&rsu=mile&country=India&q=&limit=25#content"
  },
  {
    "name": "Zoho",
    "category": "Indian SaaS",
    "sector": "SaaS Suite",
    "roles": "SDE, Python Dev",
    "ctc": "₹5–10 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://careers.zohocorp.com/jobs/Careers"
  },
  {
    "name": "InMobi",
    "category": "Indian SaaS",
    "sector": "AdTech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.inmobi.com/company/careers?country=india"
  },
  {
    "name": "Glance (InMobi)",
    "category": "Indian SaaS",
    "sector": "Content Tech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.inmobi.com/company/careers?country=india"
  },
  {
    "name": "Chargebee",
    "category": "Indian SaaS",
    "sector": "Billing SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–14 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.linkedin.com/company/chargebee/jobs/?originalSubdomain=in"
  },
  {
    "name": "MoEngage",
    "category": "Indian SaaS",
    "sector": "Engagement SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–13 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://moengage.hire.trakstar.com/"
  },
  {
    "name": "CleverTap",
    "category": "Indian SaaS",
    "sector": "Marketing SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–13 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://clevertap.com/current-openings/"
  },
  {
    "name": "Icertis",
    "category": "Indian SaaS",
    "sector": "Contract Intel",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–15 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://iaaviz.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Jobs-at-Icertis/jobs?mode=location"
  },
  {
    "name": "Darwinbox",
    "category": "Indian SaaS",
    "sector": "HR Tech SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://dbx.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Observe.AI",
    "category": "Indian SaaS",
    "sector": "AI / CX SaaS",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–14 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.observe.ai/careers"
  },
  {
    "name": "Sarvam AI",
    "category": "Indian SaaS",
    "sector": "AI / Language",
    "roles": "SDE, Python Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.sarvam.ai/careers#positions"
  },
  {
    "name": "Cashfree",
    "category": "Indian SaaS",
    "sector": "Payments",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.cashfree.com/careers/"
  },
  {
    "name": "PayU",
    "category": "Indian SaaS",
    "sector": "Payments",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://corporate.payu.com/job-board/"
  },
  {
    "name": "Pine Labs",
    "category": "Indian SaaS",
    "sector": "Merchant Payments",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.pinelabs.com/careers/open-jobs"
  },
  {
    "name": "Leadsquared",
    "category": "Indian SaaS",
    "sector": "CRM SaaS",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://leadsquaredhrms.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "WebEngage",
    "category": "Indian SaaS",
    "sector": "Marketing SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://webengage.com/current-openings/#JobOpenings"
  },
  {
    "name": "Uniphore",
    "category": "Indian SaaS",
    "sector": "Conversational AI",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://uniphore.wd503.myworkdayjobs.com/Uniphore"
  },
  {
    "name": "Exotel",
    "category": "Indian SaaS",
    "sector": "CPaaS",
    "roles": "Backend Eng, SDE",
    "ctc": "₹8–12 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://exotel.com/about-us/careers/"
  },
  {
    "name": "Capillary Tech",
    "category": "Indian SaaS",
    "sector": "Retail SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": false,
    "careers": "https://www.capillarytech.com/careers/"
  },
  {
    "name": "Locus",
    "category": "Indian SaaS",
    "sector": "Logistics SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://locus.freshteam.com/jobs"
  },
  {
    "name": "NoBroker",
    "category": "Indian SaaS",
    "sector": "PropTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.linkedin.com/jobs/search/?currentJobId=4415076028&f_C=9226228"
  },
  {
    "name": "TripJack",
    "category": "Indian SaaS",
    "sector": "Travel Tech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹6–10 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://www.tripjack.com/careers"
  },
  {
    "name": "MyGate",
    "category": "Indian SaaS",
    "sector": "Housing SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://mygate.darwinbox.in/ms/candidatev2/main/careers/home"
  },
  {
    "name": "MagicPin",
    "category": "Indian SaaS",
    "sector": "Local Commerce",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": false,
    "careers": "https://magicpin.in/careers"
  },
  {
    "name": "Tekion",
    "category": "Indian SaaS",
    "sector": "Automotive SaaS",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–22 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://tekion.com/job-openings?country=india"
  },
  {
    "name": "Hasura",
    "category": "Indian SaaS",
    "sector": "Developer Infra",
    "roles": "SDE, Backend Eng",
    "ctc": "₹12–18 LPA",
    "score": 3.3,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://jobs.gem.com/promptql"
  },
  {
    "name": "Gupshup",
    "category": "Indian SaaS",
    "sector": "CPaaS / AI",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.gupshup.io/careers"
  },
  {
    "name": "Turing",
    "category": "Indian SaaS",
    "sector": "AI / Remote Work",
    "roles": "SDE, Python Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.turing.com/jobs"
  },
  {
    "name": "Agora (100ms)",
    "category": "Indian SaaS",
    "sector": "Video Infra SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.lever.co/100ms"
  },
  {
    "name": "Zetwerk",
    "category": "Indian SaaS",
    "sector": "B2B Manufacturing",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://zetwerk.sensehq.com/careers/jobs?page=0&pageSize=10&department=&location=&title=&sortBy=&orderBy=ASC&minExp=0&maxExp=100&jobType=&workplaceType="
  },
  {
    "name": "Livespace (Livpure)",
    "category": "Indian SaaS",
    "sector": "PropTech / Design",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://careers.livspace.com/livspace/"
  },
  {
    "name": "Mudrex",
    "category": "Indian SaaS",
    "sector": "Crypto / Fintech",
    "roles": "SDE, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://mudrex.freshteam.com/jobs"
  },
  {
    "name": "Smallcase",
    "category": "Funded Startup",
    "sector": "Investing Platform",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–16 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://app.pyjamahr.com/careers?company=smallcase&company_uuid=2615584222"
  },
  {
    "name": "Jupiter Money",
    "category": "Funded Startup",
    "sector": "Neo-banking",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jupiter.keka.com/careers"
  },
  {
    "name": "Jar",
    "category": "Funded Startup",
    "sector": "Micro-savings",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.myjar.app/careers#open-roles"
  },
  {
    "name": "OneCard",
    "category": "Funded Startup",
    "sector": "Credit Card Tech",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹10–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.fplabs.tech/careers/"
  },
  {
    "name": "Niyo Solutions",
    "category": "Funded Startup",
    "sector": "Neo-banking",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://niyo.keka.com/careers"
  },
  {
    "name": "KreditBee",
    "category": "Funded Startup",
    "sector": "Lending Fintech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–13 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.kreditbee.in/careers"
  },
  {
    "name": "Axio (CapFloat)",
    "category": "Funded Startup",
    "sector": "BNPL / Lending",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://axiofinance.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Spinny",
    "category": "Funded Startup",
    "sector": "Used Cars",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://spinzone.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "CARS24",
    "category": "Funded Startup",
    "sector": "Auto Commerce",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.cars24.com/"
  },
  {
    "name": "Rebel Foods",
    "category": "Funded Startup",
    "sector": "Cloud Kitchen",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.rebelfoods.com/join-our-team"
  },
  {
    "name": "Country Delight",
    "category": "Funded Startup",
    "sector": "D2C / FoodTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.linkedin.com/jobs/country-delight-jobs/?currentJobId=4412664057&originalSubdomain=in"
  },
  {
    "name": "Licious",
    "category": "Funded Startup",
    "sector": "D2C / FoodTech",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://licious.darwinbox.in/ms/candidatev2/main/careers/allJobs\\"
  },
  {
    "name": "Purplle",
    "category": "Funded Startup",
    "sector": "Beauty E-comm",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://purplle.turbohire.co/dashboardv2?orgId=3ed17e54-f66f-4ade-90b9-ef064dc6fbd6&type=0"
  },
  {
    "name": "Mamaearth",
    "category": "Funded Startup",
    "sector": "D2C Beauty",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.linkedin.com/jobs/mamaearth-jobs/?currentJobId=4395754896&originalSubdomain=in"
  },
  {
    "name": "FirstCry",
    "category": "Funded Startup",
    "sector": "Baby Products",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.firstcry.com/careers/?srsltid=AfmBOoo6qFpi_omla37ofolGxwzg8Fstu9oaDUBMSmte_zH20uRZ32w_"
  },
  {
    "name": "MediBuddy",
    "category": "Funded Startup",
    "sector": "HealthTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–11 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://medibuddy.hire.trakstar.com/"
  },
  {
    "name": "Pocket FM",
    "category": "Funded Startup",
    "sector": "Audio Content",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.linkedin.com/jobs/pocket-fm-jobs/?currentJobId=4411594269&originalSubdomain=in"
  },
  {
    "name": "Ultrahuman",
    "category": "Funded Startup",
    "sector": "Health Wearables",
    "roles": "SDE, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://ultrahuman.zohorecruit.in/jobs/Careers?_gl=1*1diyg53*_gcl_au*NTg4ODMyODA4LjE3NzkwMjY1MDk."
  },
  {
    "name": "Freo (MoneyTap)",
    "category": "Funded Startup",
    "sector": "Credit / Lending",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://freo.money/careers/"
  },
  {
    "name": "Fibe (EarlySalary)",
    "category": "Funded Startup",
    "sector": "Lending Fintech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.2,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.fibe.in/careers/"
  },
  {
    "name": "Fi Money",
    "category": "Funded Startup",
    "sector": "Neo Banking",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.lever.co/epifi"
  },
  {
    "name": "Open Financial Technologies",
    "category": "Indian SaaS",
    "sector": "Fintech SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://open.money/careers"
  },
  {
    "name": "M2P Fintech",
    "category": "Indian SaaS",
    "sector": "Banking Infra",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.m2pfintech.com/view-jobs/"
  },
  {
    "name": "Perfios",
    "category": "Indian SaaS",
    "sector": "Fintech Data Platform",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://perfios.darwinbox.in/ms/candidatev2/main/careers/allJobs"
  },
  {
    "name": "Signzy",
    "category": "Indian SaaS",
    "sector": "AI Fintech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.signzy.com/careers"
  },
  {
    "name": "Kissflow",
    "category": "Indian SaaS",
    "sector": "Workflow SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.kissflow.com/#viewjobs"
  },
  {
    "name": "Facilio",
    "category": "Indian SaaS",
    "sector": "Property SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://facilio.com/careers/#openings"
  },
  {
    "name": "Yellow.ai",
    "category": "Indian SaaS",
    "sector": "Conversational AI",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹10–16 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://yellow.ai/career/"
  },
  {
    "name": "Rocketlane",
    "category": "Indian SaaS",
    "sector": "Customer Onboarding SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.kula.ai/rocketlane"
  },
  {
    "name": "SurveySparrow",
    "category": "Indian SaaS",
    "sector": "CX SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://surveysparrow.keka.com/careers"
  },
  {
    "name": "Krutrim",
    "category": "Indian SaaS",
    "sector": "AI Platform",
    "roles": "SDE-1, AI Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.linkedin.com/company/krutrim/jobs/"
  },
  {
    "name": "Gnani.ai",
    "category": "Indian SaaS",
    "sector": "Speech AI",
    "roles": "SDE-1, Python Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.gnani.ai/"
  },
  {
    "name": "Skit.ai",
    "category": "Indian SaaS",
    "sector": "Voice AI",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://skit.ai/careers"
  },
  {
    "name": "Mad Street Den",
    "category": "Indian SaaS",
    "sector": "Retail AI",
    "roles": "SDE-1, AI Engineer",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.madstreetden.com/careers/"
  },
  {
    "name": "Ajio",
    "category": "Indian Unicorn",
    "sector": "Fashion E-commerce",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.jio.com/"
  },
  {
    "name": "Jio Platforms",
    "category": "Indian Unicorn",
    "sector": "Digital Platforms",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://careers.jio.com/"
  },
  {
    "name": "BookMyShow",
    "category": "Indian Unicorn",
    "sector": "Entertainment Tech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://in.bookmyshow.com/careers/job-listing"
  },
  {
    "name": "Pepperfry",
    "category": "Funded Startup",
    "sector": "Furniture E-commerce",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.pepperfry.com/pages/careers.html?type=footer"
  },
  {
    "name": "Nazara Technologies",
    "category": "Indian Unicorn",
    "sector": "Gaming",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://nazara.com/careers"
  },
  {
    "name": "WinZO",
    "category": "Indian Unicorn",
    "sector": "Gaming Platform",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://winzogames.com/careers"
  },
  {
    "name": "Josh",
    "category": "Indian Unicorn",
    "sector": "Short Video Platform",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://careers.dailyhunt.in"
  },
  {
    "name": "Healthify",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://healthify.darwinbox.in/ms/candidatev2/main/careers/home"
  },
  {
    "name": "Apollo 24/7",
    "category": "Indian Unicorn",
    "sector": "HealthTech",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://cgs.fa.ap2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2/"
  },
  {
    "name": "Teachmint",
    "category": "Funded Startup",
    "sector": "EdTech SaaS",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://teachmint.com/careers"
  },
  {
    "name": "Classplus",
    "category": "Funded Startup",
    "sector": "EdTech Infrastructure",
    "roles": "SDE-1, Backend Dev",
    "ctc": "₹7–12 LPA",
    "score": 2.4,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://classplusapp.com/careers/open-role"
  },
  {
    "name": "ServiceNow",
    "category": "Global MNC",
    "sector": "Enterprise SaaS",
    "roles": "SWE, Backend Eng",
    "ctc": "₹15–25 LPA",
    "score": 3.1,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.servicenow.com/jobs/?search=&country=India&pagesize=20#results"
  },
  {
    "name": "Infor",
    "category": "Global MNC",
    "sector": "Enterprise Cloud Software",
    "roles": "Software Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://infor.pinpointhq.com/"
  },
  {
    "name": "Thomson Reuters",
    "category": "Global MNC",
    "sector": "LegalTech / Fintech",
    "roles": "Software Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://thomsonreuters.wd5.myworkdayjobs.com/en-US/External_Career_Site"
  },
  {
    "name": "EPAM Systems",
    "category": "Global MNC",
    "sector": "Product Engineering",
    "roles": "Software Engineer",
    "ctc": "₹8–16 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.epam.com/en/jobs/india"
  },
  {
    "name": "Siemens",
    "category": "Global MNC",
    "sector": "Industrial Software",
    "roles": "Software Engineer",
    "ctc": "₹8–16 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://jobs.siemens.com/en_US/externaljobs/SearchJobs"
  },
  {
    "name": "Nutanix",
    "category": "Global MNC",
    "sector": "Cloud Infrastructure",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹14–22 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.nutanix.com/en/jobs/?search=&country=India&pagesize=20#results"
  },
  {
    "name": "Vanguard",
    "category": "Global MNC",
    "sector": "Investment Tech",
    "roles": "AI Engineer, Cloud Engineer",
    "ctc": "₹14–24 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.vanguardjobs.com/job-search-results/?location=IN%2C%20Telangana%2C%20Hyderabad"
  },
  {
    "name": "Wells Fargo",
    "category": "Global MNC",
    "sector": "Banking Tech",
    "roles": "Java Fullstack Dev, Backend Eng",
    "ctc": "₹12–22 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.wellsfargojobs.com/en/jobs/?search=&country="
  },
  {
    "name": "Deutsche Bank",
    "category": "Global MNC",
    "sector": "Fintech / Banking",
    "roles": "Backend Developer, SDE-1",
    "ctc": "₹12–22 LPA",
    "score": 3,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.db.com/professionals/search-roles/index?language_id=1#/professional/results/?searchType=divisionProf"
  },
  {
    "name": "BMC Software",
    "category": "Global MNC",
    "sector": "Enterprise IT",
    "roles": "Automation Engineer, Backend Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.bmc.com/Careers/SearchJobs/?listFilterMode=1&1274=9406&1274_format=1347&intcmp=JobsByCountry"
  },
  {
    "name": "Persistent Systems",
    "category": "Indian SaaS",
    "sector": "Digital Engineering",
    "roles": "Python Backend Dev, SDE-1",
    "ctc": "₹8–16 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.persistent.com/explore-opportunities"
  },
  {
    "name": "McDonald's Global Technology Hub",
    "category": "Global MNC",
    "sector": "Retail Tech",
    "roles": "Software Engineer, Fullstack Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.mcdonalds.com/jobs?filter%5Bcountry%5D%5B0%5D=IN"
  },
  {
    "name": "Applied Intuition",
    "category": "Funded Startup",
    "sector": "Autonomous Vehicles",
    "roles": "Software Engineer, Backend Dev",
    "ctc": "₹14–24 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.appliedintuition.com/careers"
  },
  {
    "name": "Impact Analytics",
    "category": "Funded Startup",
    "sector": "AI Analytics",
    "roles": "AI Engineer, Python Dev",
    "ctc": "₹8–16 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.impactanalytics.ai/careers#jobs"
  },
  {
    "name": "Redio AI",
    "category": "Funded Startup",
    "sector": "Healthcare AI",
    "roles": "Python Dev, Backend Eng",
    "ctc": "₹8–14 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://redio.ai/careers"
  },
  {
    "name": "Soft Suave",
    "category": "Funded Startup",
    "sector": "Product Engineering",
    "roles": "Python Developer, Backend Dev",
    "ctc": "₹6–10 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.softsuave.com/career-overview"
  },
  {
    "name": "eSparkBiz",
    "category": "Funded Startup",
    "sector": "Enterprise SaaS",
    "roles": "Python Dev, Fullstack Dev",
    "ctc": "₹6–10 LPA",
    "score": 2.3,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://www.esparkinfo.com/about/career"
  },
  {
    "name": "Databricks",
    "category": "Global MNC",
    "sector": "Data / AI Platform",
    "roles": "Backend Engineer, Platform Eng",
    "ctc": "₹18–30 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.databricks.com/company/careers/open-positions?department=all&location=India"
  },
  {
    "name": "Costco Technology",
    "category": "Global MNC",
    "sector": "Retail Tech",
    "roles": "Product Developer, SDE-1",
    "ctc": "₹10–18 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.costco.com/jobs?stretchUnit=MILES&stretch=10&location=India&woe=12&regionCode=IN"
  },
  {
    "name": "JPMorgan Chase",
    "category": "Irrelevant",
    "sector": "Banking GCC",
    "roles": "Java Backend, Banking Platforms",
    "ctc": "₹12–24 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?location=India&locationId=300000000289360&locationLevel=country&mode=location"
  },
  {
    "name": "Novartis",
    "category": "Irrelevant",
    "sector": "Pharma Tech",
    "roles": "AI Engineer, Data Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.novartis.com/careers/career-search?search_api_fulltext=&field_job_posted_date=All&op=Submit"
  },
  {
    "name": "Sanofi",
    "category": "Irrelevant",
    "sector": "Pharmaceuticals",
    "roles": "Software Engineer, AI Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.sanofi.com/en/search-jobs"
  },
  {
    "name": "Eli Lilly",
    "category": "Irrelevant",
    "sector": "Healthcare AI",
    "roles": "AI/ML Engineer, Backend Dev",
    "ctc": "₹12–20 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.lilly.com/us/en/search-results?keywords="
  },
  {
    "name": "Bristol Myers Squibb",
    "category": "Irrelevant",
    "sector": "Biopharma Tech",
    "roles": "Software Engineer, Data Engineer",
    "ctc": "₹10–18 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://careers.bms.com/"
  },
  {
    "name": "Mercedes-Benz",
    "category": "Irrelevant",
    "sector": "Automotive Software",
    "roles": "Platform Engineer, Embedded Dev",
    "ctc": "₹12–22 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.mercedes-benz.com/en?TargetGroup.Code=3"
  },
  {
    "name": "Volkswagen",
    "category": "Irrelevant",
    "sector": "Automotive IT",
    "roles": "Software Engineer, Backend Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.volkswagenag.com/en/group/career.html"
  },
  {
    "name": "Bosch",
    "category": "Irrelevant",
    "sector": "Industrial / Embedded",
    "roles": "Embedded Engineer, Software Dev",
    "ctc": "₹8–16 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://jobs.bosch.com/en/?pages=1&country=in"
  },
  {
    "name": "Ford",
    "category": "Irrelevant",
    "sector": "Automotive Analytics",
    "roles": "Data Scientist, Backend Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.6,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.careers.ford.com/search-jobs?orgIds=48560&ac=9255664"
  },
  {
    "name": "Caterpillar",
    "category": "Irrelevant",
    "sector": "Industrial Engineering",
    "roles": "Fullstack Engineer, IoT Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.5,
    "diff": "Easy",
    "isnew": true,
    "careers": "https://careers.caterpillar.com"
  },
  {
    "name": "Datadog",
    "category": "Global MNC",
    "sector": "Observability Platform",
    "roles": "Backend Engineer, Platform Dev",
    "ctc": "₹18–30 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://careers.datadoghq.com/all-jobs/?location_APAC%5B0%5D=Mumbai&location_APAC%5B1%5D=Delhi&location_APAC%5B2%5D=Bangalore"
  },
  {
    "name": "Confluent",
    "category": "Global MNC",
    "sector": "Data Streaming",
    "roles": "Backend Engineer, Infra Dev",
    "ctc": "₹18–32 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://careers.confluent.io/jobs/india"
  },
  {
    "name": "Elastic",
    "category": "Global MNC",
    "sector": "Search Infrastructure",
    "roles": "Backend Engineer, Platform Dev",
    "ctc": "₹16–28 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://jobs.elastic.co/jobs/country/india?size=n_20_n"
  },
  {
    "name": "Rubrik",
    "category": "Global MNC",
    "sector": "Cloud Data Security",
    "roles": "SDE-1, Backend Eng",
    "ctc": "₹18–30 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.rubrik.com/company/careers/departments/engineering"
  },
  {
    "name": "Cohesity",
    "category": "Global MNC",
    "sector": "Data Security",
    "roles": "Software Engineer, Platform Eng",
    "ctc": "₹16–28 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.cohesity.com/careers/open-positions/"
  },
  {
    "name": "Harness",
    "category": "Indian SaaS",
    "sector": "Developer Productivity",
    "roles": "Backend Engineer, DevOps Dev",
    "ctc": "₹14–24 LPA",
    "score": 3.2,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://www.harness.io/company/jobs"
  },
  {
    "name": "GitLab",
    "category": "Global MNC",
    "sector": "DevOps Platform",
    "roles": "Backend Engineer, Fullstack Dev",
    "ctc": "₹18–32 LPA",
    "score": 3.5,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://about.gitlab.com/jobs/all-jobs/"
  },
  {
    "name": "Docker",
    "category": "Global MNC",
    "sector": "Container Platform",
    "roles": "Platform Engineer, Backend Dev",
    "ctc": "₹16–28 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.docker.com/career-openings/"
  },
  {
    "name": "Palo Alto Networks",
    "category": "Global MNC",
    "sector": "Cybersecurity",
    "roles": "Security Engineer, Backend Dev",
    "ctc": "₹18–32 LPA",
    "score": 3.6,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://jobs.paloaltonetworks.com/en/search-jobs/India/India/47263/1/2/1269750/22/79/50/2"
  },
  {
    "name": "CrowdStrike",
    "category": "Global MNC",
    "sector": "Cloud Security",
    "roles": "Backend Engineer, Security Dev",
    "ctc": "₹18–32 LPA",
    "score": 3.6,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e"
  },
  {
    "name": "Zscaler",
    "category": "Global MNC",
    "sector": "Cloud Security",
    "roles": "Software Engineer, Platform Dev",
    "ctc": "₹16–28 LPA",
    "score": 3.4,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://www.zscaler.com/careers/search?locations=India&page=1"
  },
  {
    "name": "Niramai",
    "category": "Funded Startup",
    "sector": "Healthcare AI",
    "roles": "AI Engineer, Python Dev",
    "ctc": "₹8–14 LPA",
    "score": 2.7,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://niramai.com/careers/"
  },
  {
    "name": "Haptik",
    "category": "Indian SaaS",
    "sector": "Conversational AI",
    "roles": "Backend Engineer, AI Dev",
    "ctc": "₹8–16 LPA",
    "score": 2.8,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://haptik.freshteam.com/jobs?__hstc=233858945.0eecb6901547789a76a8150b48139b47.1650872173205.1656650197197.1656654941825.85&__hssc=233858945.2.1656654941825&__hsfp=&hsCtaTracking=be1d0f38-8578-466c-a65e-7dba125d958a%7C852c3dbe-26c9-4a01-a174-ad02a06686d9&_gl=1*1lgi0yc*_gcl_au*MjEwNjgzMDMyOC4xNzc5MDMwNzE1*_ga*NzA0MDk3MzMuMTc3OTAzMDcwNw..*_ga_TL7ZLD0W5B*czE3NzkwMzA3MDYkbzEkZzAkdDE3NzkwMzA3MDYkajYwJGwwJGgw"
  },
  {
    "name": "Rephrase.ai",
    "category": "Funded Startup",
    "sector": "Generative AI",
    "roles": "AI Engineer, Backend Dev",
    "ctc": "₹10–18 LPA",
    "score": 2.9,
    "diff": "Medium",
    "isnew": true,
    "careers": "https://rephrase.ai/careers"
  },
  {
    "name": "NVIDIA",
    "category": "Global MNC",
    "sector": "GPU / AI Hardware",
    "roles": "Software Engineer, CUDA Dev",
    "ctc": "₹20–40 LPA",
    "score": 3.8,
    "diff": "Hard",
    "isnew": true,
    "careers": "https://jobs.nvidia.com/careers?utm_source=sp_auto_dm&utm_referrer=sp_auto_dm&start=0&location=india&pid=893392494148&sort_by=distance&filter_include_remote=1"
  }
];
